# Generated by Django 5.1.2 on 2024-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.IntegerField()),
                ('id_vehiculo', models.IntegerField()),
                ('id_empleado', models.IntegerField()),
                ('tipo_mantenimiento', models.CharField(max_length=255)),
            ],
        ),
    ]
