# Generated by Django 5.1.2 on 2024-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
            ],
        ),
    ]
